// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.onetastefamily.com/support",
            "email": "support@onetastefamily.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/captcha": {
            "get": {
                "description": "获取一个带干扰的图形验证码图片及对应的编码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "获取图形验证码",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "图片宽度（120-360），默认220",
                        "name": "width",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "图片高度（40-160），默认70",
                        "name": "height",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CaptchaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "用户登录接口，支持手机号和密码登录。登录成功后返回用户ID、JWT Token和过期时间。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "手机号或密码错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "用户注册接口，支持手机号、密码、验证码、昵称注册。注册成功后返回用户ID和JWT Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误、验证码错误或手机号已注册",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/dishes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按照家庭返回菜式列表，支持按分类和名称关键字筛选。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜式"
                ],
                "summary": "获取菜式列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（默认1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量（默认20，最大100）",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "菜式分类",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称关键字",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.DishListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "尚未加入家庭",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "向当前家庭食谱库添加菜式，至少包含一个食材和一个烹饪步骤。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜式"
                ],
                "summary": "创建菜式",
                "parameters": [
                    {
                        "description": "创建菜式请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateDishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.DishCreateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或业务限制",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "尚未加入家庭",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/dishes/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回菜式的食材和烹饪步骤信息。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜式"
                ],
                "summary": "获取菜式详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜式ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.DishDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "菜式或家庭不存在",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "仅允许菜式创建者或家庭管理员编辑菜式。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜式"
                ],
                "summary": "更新菜式",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜式ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新菜式请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateDishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.DishDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或业务限制",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "菜式或家庭不存在",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "仅允许菜式创建者或家庭管理员删除菜式。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜式"
                ],
                "summary": "删除菜式",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜式ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "菜式或家庭不存在",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/family/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一个新的家庭，创建者自动成为owner并加入家庭。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "家庭"
                ],
                "summary": "创建家庭",
                "parameters": [
                    {
                        "description": "创建家庭请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateFamilyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.FamilyResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误或已加入家庭",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权或Token无效",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/family/info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户所属家庭信息，包括成员数量与菜式数量。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "家庭"
                ],
                "summary": "获取家庭信息",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.FamilyInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权或Token无效",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "尚未创建或加入家庭",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/family/member/invite": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户在前端点击“同意”后调用该接口，加入邀请人所在家庭。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "家庭"
                ],
                "summary": "扫码加入家庭",
                "parameters": [
                    {
                        "description": "扫码加入家庭请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FamilyInviteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "加入成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.FamilyJoinResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或业务限制",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权或Token无效",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "家庭不存在或邀请无效",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/family/members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回当前用户所属家庭的成员列表。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "家庭"
                ],
                "summary": "获取家庭成员列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.FamilyMemberInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权或Token无效",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "尚未创建或加入家庭",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务是否正常运行",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ingredients/by-category": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户根据分类浏览基础食材",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "食材"
                ],
                "summary": "按分类分页查询食材",
                "parameters": [
                    {
                        "type": "string",
                        "description": "食材分类",
                        "name": "category",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分类内模糊搜索",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.IngredientCategoryListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/ingredients/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据关键字返回最多10条可用基础食材",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "食材"
                ],
                "summary": "食材模糊搜索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键字",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "返回条数 (1-20, 默认10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "搜索成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/media/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传图片等媒体文件，并返回可访问地址。需要 Bearer Token。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "媒体"
                ],
                "summary": "上传媒体文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "待上传文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件目录前缀，例如 /user/head/{userId}、/family/{familyId}/dishes/{dishId}",
                        "name": "path",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.MediaUploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/menus": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为某一天某一餐创建菜单，支持日期、餐次（早餐/午餐/晚餐）、菜式列表输入。同一日期同一餐次只能有一个菜单，可以覆盖已有菜单。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单"
                ],
                "summary": "创建菜单",
                "parameters": [
                    {
                        "description": "创建菜单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.MenuCreateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或业务限制",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "尚未加入家庭或菜式不存在",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/menus/daily": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取某一天的三餐菜单（早餐、午餐、晚餐）。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单"
                ],
                "summary": "获取每日菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期，格式：YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.DailyMenuResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "尚未加入家庭",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/menus/weekly": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取从开始日期起一周的菜单列表。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单"
                ],
                "summary": "获取每周菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始日期，格式：YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.WeeklyMenuResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "尚未加入家庭",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/menus/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新已有菜单，支持添加菜式、删除菜式、修改日期或餐次。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单"
                ],
                "summary": "更新菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新菜单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.MenuUpdateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或业务限制",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "菜单或家庭不存在",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的基本信息和会员状态。需要Bearer Token认证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权或Token无效",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CaptchaResponse": {
            "description": "图形验证码返回数据",
            "type": "object",
            "properties": {
                "captcha_key": {
                    "description": "验证码编码",
                    "type": "string",
                    "example": "01J0XYZABCD1234EFG567HIJK"
                },
                "expire_in": {
                    "description": "过期时间（秒）",
                    "type": "integer",
                    "example": 30
                },
                "image_base64": {
                    "description": "图形验证码Base64",
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUg..."
                }
            }
        },
        "models.CookingStep": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "step_id": {
                    "type": "string"
                }
            }
        },
        "models.CookingStepInput": {
            "type": "object",
            "required": [
                "content",
                "order"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 2000
                },
                "image_url": {
                    "type": "string",
                    "maxLength": 500
                },
                "order": {
                    "type": "integer",
                    "maximum": 200,
                    "minimum": 1
                }
            }
        },
        "models.CreateDishRequest": {
            "type": "object",
            "required": [
                "ingredients",
                "name",
                "steps"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "maxLength": 50
                },
                "description": {
                    "type": "string",
                    "maxLength": 2000
                },
                "image_url": {
                    "type": "string",
                    "maxLength": 500
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IngredientInput"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CookingStepInput"
                    }
                }
            }
        },
        "models.CreateFamilyRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "description": "家庭描述，可选",
                    "type": "string",
                    "maxLength": 500,
                    "example": "温馨的家庭"
                },
                "name": {
                    "description": "家庭名称",
                    "type": "string",
                    "maxLength": 100,
                    "example": "张家的厨房"
                }
            }
        },
        "models.CreateMenuRequest": {
            "type": "object",
            "required": [
                "date",
                "dish_ids",
                "meal_type"
            ],
            "properties": {
                "date": {
                    "description": "日期，格式：YYYY-MM-DD",
                    "type": "string"
                },
                "dish_ids": {
                    "description": "菜式ID列表，至少1个",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "meal_type": {
                    "description": "餐次",
                    "type": "string",
                    "enum": [
                        "breakfast",
                        "lunch",
                        "dinner"
                    ]
                }
            }
        },
        "models.DailyMenuResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "menus": {
                    "description": "三餐菜单（早餐、午餐、晚餐）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MenuDetail"
                    }
                }
            }
        },
        "models.DishCreateResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dish_id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Ingredient"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.DishDetailResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dish_id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Ingredient"
                    }
                },
                "name": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CookingStep"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.DishListResponse": {
            "type": "object",
            "properties": {
                "dishes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DishSummary"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.DishSummary": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dish_id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.FamilyInfoResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "温馨的家庭"
                },
                "dish_count": {
                    "type": "integer",
                    "example": 15
                },
                "family_id": {
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6P"
                },
                "max_dishes": {
                    "type": "integer",
                    "example": 30
                },
                "member_count": {
                    "type": "integer",
                    "example": 3
                },
                "name": {
                    "type": "string",
                    "example": "张家的厨房"
                },
                "owner_id": {
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6Q"
                }
            }
        },
        "models.FamilyInviteRequest": {
            "type": "object",
            "required": [
                "action",
                "family_id",
                "family_name",
                "inviter_id",
                "inviter_nickname"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "example": "accept"
                },
                "family_id": {
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6P"
                },
                "family_name": {
                    "type": "string",
                    "example": "张家的厨房"
                },
                "inviter_id": {
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6Q"
                },
                "inviter_nickname": {
                    "type": "string",
                    "example": "张三"
                }
            }
        },
        "models.FamilyJoinResponse": {
            "type": "object",
            "properties": {
                "family_id": {
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6P"
                },
                "joined_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "member_role": {
                    "type": "string",
                    "example": "member"
                }
            }
        },
        "models.FamilyMemberInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://.../avatar.jpg"
                },
                "joined_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "nickname": {
                    "type": "string",
                    "example": "李四"
                },
                "role": {
                    "type": "string",
                    "example": "member"
                },
                "user_id": {
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6R"
                }
            }
        },
        "models.FamilyResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "温馨的家庭"
                },
                "family_id": {
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6P"
                },
                "max_dishes": {
                    "type": "integer",
                    "example": 30
                },
                "member_count": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "张家的厨房"
                }
            }
        },
        "models.Ingredient": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "default_unit": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ingredient_id": {
                    "type": "string"
                },
                "ingredient_name": {
                    "type": "string"
                },
                "ingredient_name_en": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                },
                "storage_days": {
                    "type": "integer"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "models.IngredientCategoryListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IngredientSearchResult"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.IngredientInput": {
            "type": "object",
            "required": [
                "amount",
                "ingredient_id",
                "unit"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "ingredient_id": {
                    "type": "string",
                    "maxLength": 26,
                    "minLength": 1
                },
                "notes": {
                    "type": "string",
                    "maxLength": 255
                },
                "sort_order": {
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 0
                },
                "unit": {
                    "type": "string",
                    "maxLength": 20
                }
            }
        },
        "models.IngredientSearchResult": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "default_unit": {
                    "type": "string"
                },
                "ingredient_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "storage_days": {
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "description": "用户登录请求参数",
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "password123"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "example": "13800138000"
                }
            }
        },
        "models.LoginResponse": {
            "description": "用户登录成功返回的数据",
            "type": "object",
            "properties": {
                "expires_in": {
                    "description": "Token过期时间（秒）",
                    "type": "integer",
                    "example": 86400
                },
                "token": {
                    "description": "JWT Token",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "description": "用户ID",
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6P"
                }
            }
        },
        "models.MediaUploadResponse": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "directory": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "object_key": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.MembershipInfo": {
            "description": "用户会员信息",
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "到期时间，免费版为null",
                    "type": "string",
                    "example": "2024-12-31T23:59:59Z"
                },
                "type": {
                    "description": "会员类型：free-免费版，premium-付费版",
                    "type": "string",
                    "example": "free"
                }
            }
        },
        "models.MenuCreateResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "dishes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DishSummary"
                    }
                },
                "meal_type": {
                    "type": "string"
                },
                "menu_id": {
                    "type": "string"
                }
            }
        },
        "models.MenuDetail": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "date": {
                    "description": "格式：YYYY-MM-DD",
                    "type": "string"
                },
                "dishes": {
                    "description": "菜式列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DishSummary"
                    }
                },
                "family_id": {
                    "type": "string"
                },
                "meal_type": {
                    "description": "breakfast, lunch, dinner",
                    "type": "string"
                },
                "menu_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.MenuUpdateResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "date": {
                    "description": "格式：YYYY-MM-DD",
                    "type": "string"
                },
                "dishes": {
                    "description": "菜式列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DishSummary"
                    }
                },
                "family_id": {
                    "type": "string"
                },
                "meal_type": {
                    "description": "breakfast, lunch, dinner",
                    "type": "string"
                },
                "menu_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.RegisterRequest": {
            "description": "用户注册请求参数",
            "type": "object",
            "required": [
                "captcha_key",
                "nickname",
                "password",
                "phone",
                "verify_code"
            ],
            "properties": {
                "captcha_key": {
                    "description": "验证码编码",
                    "type": "string",
                    "example": "01J0XYZABCD1234EFG567HIJK"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string",
                    "example": "张三"
                },
                "password": {
                    "description": "密码，至少6位",
                    "type": "string",
                    "minLength": 6,
                    "example": "password123"
                },
                "phone": {
                    "description": "手机号，11位数字",
                    "type": "string",
                    "example": "13800138000"
                },
                "verify_code": {
                    "description": "图形验证码内容，不区分大小写",
                    "type": "string",
                    "example": "A9d3"
                }
            }
        },
        "models.RegisterResponse": {
            "description": "用户注册成功返回的数据",
            "type": "object",
            "properties": {
                "token": {
                    "description": "JWT Token",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "description": "用户ID",
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6P"
                }
            }
        },
        "models.UpdateDishRequest": {
            "type": "object",
            "required": [
                "ingredients",
                "name",
                "steps"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "maxLength": 50
                },
                "description": {
                    "type": "string",
                    "maxLength": 2000
                },
                "image_url": {
                    "type": "string",
                    "maxLength": 500
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IngredientInput"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CookingStepInput"
                    }
                }
            }
        },
        "models.UpdateMenuRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "日期，格式：YYYY-MM-DD",
                    "type": "string"
                },
                "dish_ids": {
                    "description": "菜式ID列表",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "meal_type": {
                    "description": "餐次",
                    "type": "string",
                    "enum": [
                        "breakfast",
                        "lunch",
                        "dinner"
                    ]
                }
            }
        },
        "models.UserInfoResponse": {
            "description": "用户信息返回数据",
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像URL",
                    "type": "string",
                    "example": "https://..."
                },
                "membership": {
                    "description": "会员信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MembershipInfo"
                        }
                    ]
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string",
                    "example": "张三"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "example": "13800138000"
                },
                "user_id": {
                    "description": "用户ID",
                    "type": "string",
                    "example": "01HZX1YF8Y6S7K4V9Q2J3M5N6P"
                }
            }
        },
        "models.WeeklyMenuResponse": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "menus": {
                    "description": "一周的菜单列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MenuDetail"
                    }
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "utils.FieldError": {
            "description": "字段验证错误信息",
            "type": "object",
            "properties": {
                "field": {
                    "description": "错误字段名",
                    "type": "string",
                    "example": "phone"
                },
                "message": {
                    "description": "错误消息",
                    "type": "string",
                    "example": "手机号格式不正确"
                }
            }
        },
        "utils.Response": {
            "description": "统一的API响应格式",
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据"
                },
                "errors": {
                    "description": "字段错误列表（仅在错误时返回）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.FieldError"
                    }
                },
                "message": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "success"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "使用 \"Bearer {token}\" 格式，token 通过登录接口获取",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "OneTaste Family API",
	Description:      "家庭饮食管理系统的后端API接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
